---
# tasks file for grafana

- name: Ensure devops namespace exists
  k8s:
    state: present
    definition: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ devops_namespace }}"

- name: Apply grafana deployment
  k8s:
    state: present
    definition: "{{ lookup('file', 'files/deployment.yaml') }}"

- name: Apply grafana service
  k8s:
    state: present
    definition: "{{ lookup('file', 'files/service.yaml') }}"