---
# tasks file for jenkins_deploy

- name: Ensure jenkins namespace exists
  k8s:
    state: present
    definition: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ jenkins_namespace }}"

- name: Apply Jenkins deployment
  k8s:
    state: present
    definition: "{{ lookup('file', 'files/deployment.yaml') }}"

- name: Apply Jenkins service
  k8s:
    state: present
    definition: "{{ lookup('file', 'files/service.yaml') }}"
